import * as EnumsValues from '../enums/selectEnums';

export const detailedRequestForm = [
    {
      label: 'Category',
      bindTo: 'requestCategory',
      questionType: 'select',
      selectOptionsEnum: EnumsValues.categoryOptionsEnglish,
      validators: {},
      section: 'Request details',
    },
    {
      label: 'Tangible or service',
      bindTo: 'requestProductType',
      questionType: 'select',
      selectOptionsEnum: EnumsValues.productTypeOptions,
      validators: {},
      section: 'Request details',
    },
    {
      label: 'Product name',
      bindTo: 'productName',
      questionType: 'input',
      inputType: 'text',
      validators: {},
      section: 'Request details',
    },
    {
      label: 'Crated on',
      bindTo: 'createdOn',
      questionType: 'input',
      inputType: 'text',
      validators: {},
      section: 'Request details',
    },
    {
      label: 'Offers received',
      bindTo: 'offersReceivedAmount',
      questionType: 'input',
      inputType: 'numbr',
      validators: {},
      section: 'Request details',
    },
    {
      label: 'Buying frequenty',
      bindTo: 'buyingFrequenty',
      questionType: 'select',
      selectOptionsEnum: EnumsValues.buyingFrequesnty,
      validators: {},
      section: 'Order details',
    },
    {
      label: 'Unit defenition',
      bindTo: 'unitDefenition',
      questionType: 'input',
      inputType: 'text',
      validators: {},
      section: 'Order details',
    },
    {
      label: 'Current unit price',
      bindTo: 'requestCurrentUnitPrice',
      questionType: 'input',
      inputType: 'currency',
      validators: {},
      section: 'Order details',
    },
    {
      label: 'Target unit price',
      bindTo: 'requestTargetUnitPrice',
      questionType: 'input',
      inputType: 'currency',
      validators: {},
      section: 'Order details',
    },
    {
      label: 'Estimated yearly value',
      bindTo: 'yearlyValue',
      questionType: 'input',
      inputType: 'currency',
      validators: {},
      section: 'Order details',
    },
  ];